# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cmd_str', models.CharField(max_length=512)),
                ('return_code', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommandOnResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_hash', models.CharField(max_length=64)),
                ('resource_size', models.BigIntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chitin_meta.Command')),
            ],
        ),
        migrations.CreateModel(
            name='MetaRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_tag', models.CharField(db_index=True, max_length=64)),
                ('meta_name', models.CharField(max_length=64)),
                ('value_type', models.CharField(max_length=48)),
                ('value', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chitin_meta.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_path', models.CharField(max_length=512)),
                ('current_hash', models.CharField(max_length=64)),
                ('current_size', models.BigIntegerField(default=0)),
                ('ghost', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='current_master_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chitin_meta.ResourceGroup'),
        ),
        migrations.AddField(
            model_name='resource',
            name='current_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chitin_meta.Node'),
        ),
        migrations.AddField(
            model_name='metarecord',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chitin_meta.Resource'),
        ),
        migrations.AddField(
            model_name='commandonresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chitin_meta.Resource'),
        ),
    ]
