# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chitin_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 13, 29, 51, 447302, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='queued_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 13, 29, 57, 189777, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 13, 30, 5, 103550, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandonresource',
            name='effect_status',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandonresource',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='chitin_meta.Command'),
        ),
    ]
