# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitin_meta', '0002_auto_20180922_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='user',
            field=models.CharField(default='somebody', max_length=32),
            preserve_default=False,
        ),
    ]
