# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitin_meta', '0003_command_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='return_code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
