# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitin_meta', '0005_auto_20180922_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='group_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
