# Generated by Django 2.2.10 on 2020-05-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tatl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatlrequest',
            name='substitute_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='su_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
