# Generated by Django 2.2.10 on 2020-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0002_tatlrequest_substitute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatlrequest',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
