# Generated by Django 2.2.10 on 2020-05-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0004_tatlpermflex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatlpermflex',
            name='extra_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
