# Generated by Django 2.2.13 on 2020-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0006_tatlrequest_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatlrequest',
            name='response_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
