# Generated by Django 2.2.13 on 2020-08-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0009_auto_20200807_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatlpermflex',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action', to='tatl.TatlRequest'),
        ),
    ]
