# Generated by Django 2.2.13 on 2020-08-22 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tatl', '0010_auto_20200814_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='TatlPageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.CharField(blank=True, max_length=48, null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
