# Generated by Django 2.2.13 on 2020-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0012_tatlpagerequest_view_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatlpagerequest',
            name='view_path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
