# Generated by Django 2.2.13 on 2020-08-22 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0013_tatlpagerequest_view_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatlpagerequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
