# Generated by Django 2.2.13 on 2020-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0014_auto_20200822_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatlpagerequest',
            name='params',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='tatlpagerequest',
            name='payload',
            field=models.TextField(default='{}'),
        ),
    ]
