# Generated by Django 2.2.13 on 2020-08-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0016_auto_20200822_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tatlrequest',
            old_name='route',
            new_name='view_path',
        ),
    ]
