# Generated by Django 2.2.13 on 2020-08-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0017_auto_20200822_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatlrequest',
            name='params',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='tatlrequest',
            name='view_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tatlrequest',
            name='payload',
            field=models.TextField(default='{}'),
        ),
    ]
