# Generated by Django 2.2.13 on 2020-08-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0019_tatlrequest_status_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TatlPageRequest',
        ),
    ]
