# Generated by Django 2.2.13 on 2020-08-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0021_auto_20200822_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatlrequest',
            name='is_api',
            field=models.BooleanField(default=True),
        ),
    ]
