# Generated by Django 2.2.13 on 2020-08-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tatl', '0022_tatlrequest_is_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatlrequest',
            name='is_api',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TatlVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=10)),
                ('object_id', models.CharField(max_length=64)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verbs', to='tatl.TatlRequest')),
            ],
        ),
    ]
