# Generated by Django 2.2.13 on 2021-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0026_tatlverb_extra_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatlverb',
            name='object_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
