# Generated by Django 2.1.4 on 2019-08-18 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajoraArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dice_name', models.CharField(blank=True, max_length=48, null=True)),
                ('meta_name', models.CharField(blank=True, max_length=48, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MajoraArtifactGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dice_name', models.CharField(blank=True, max_length=48, null=True)),
                ('meta_name', models.CharField(blank=True, max_length=48, null=True)),
                ('physical', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MajoraArtifactProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('when', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MajoraArtifactProcessGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='tagged_groups', to='majora2.MajoraArtifactProcessGroup')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='majora2.MajoraArtifactProcessGroup')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifactprocessgroup_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MajoraArtifactProcessRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DigitalResourceArtifact',
            fields=[
                ('majoraartifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifact')),
                ('current_name', models.CharField(max_length=512)),
                ('current_hash', models.CharField(max_length=64)),
                ('current_size', models.BigIntegerField(default=0)),
                ('ghost', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifact',),
        ),
        migrations.CreateModel(
            name='DigitalResourceGroup',
            fields=[
                ('majoraartifactgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactGroup')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactgroup',),
        ),
        migrations.CreateModel(
            name='TubeArtifact',
            fields=[
                ('majoraartifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifact')),
                ('container_x', models.PositiveSmallIntegerField()),
                ('container_y', models.PositiveSmallIntegerField()),
                ('container_z', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('storage_medium', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifact',),
        ),
        migrations.CreateModel(
            name='TubeContainerGroup',
            fields=[
                ('majoraartifactgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactGroup')),
                ('container_type', models.CharField(max_length=24)),
                ('contains_tubes', models.BooleanField(default=False)),
                ('dimension_x', models.PositiveSmallIntegerField()),
                ('dimension_y', models.PositiveSmallIntegerField()),
                ('parent_x', models.PositiveSmallIntegerField()),
                ('parent_y', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactgroup',),
        ),
        migrations.AddField(
            model_name='majoraartifactprocessrecord',
            name='in_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='before_process', to='majora2.MajoraArtifact'),
        ),
        migrations.AddField(
            model_name='majoraartifactprocessrecord',
            name='out_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_process', to='majora2.MajoraArtifact'),
        ),
        migrations.AddField(
            model_name='majoraartifactprocessrecord',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifactprocessrecord_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='majoraartifactprocessrecord',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majora2.MajoraArtifactProcess'),
        ),
        migrations.AddField(
            model_name='majoraartifactprocess',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majora2.MajoraArtifactProcessGroup'),
        ),
        migrations.AddField(
            model_name='majoraartifactprocess',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifactprocess_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='majoraartifactprocess',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tagged_groups', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifactgroup_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='root_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descendants', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AddField(
            model_name='majoraartifact',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tagged_artifacts', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AddField(
            model_name='majoraartifact',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifact_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='majoraartifact',
            name='primary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='majora2.MajoraArtifactGroup'),
        ),
    ]
