# Generated by Django 2.1.4 on 2019-08-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajoraArtifactProcessRecordTest',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
                ('test_message', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
        migrations.CreateModel(
            name='MajoraArtifactProcessTest',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
                ('test_message', models.CharField(max_length=256)),
                ('test_user', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.RemoveField(
            model_name='digitalresourcegroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tubeartifact',
            name='container_z',
        ),
    ]
