# Generated by Django 2.1.4 on 2019-08-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0002_auto_20190818_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalresourcegroup',
            name='current_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
