# Generated by Django 2.2.10 on 2020-03-18 10:51

from django.db import migrations

def make_institute(apps, schema_editor):
    Profile = apps.get_model("majora2", "Profile")
    Institute = apps.get_model("majora2", "Institute")
    for profile in Profile.objects.all():
        institute, created = Institute.objects.get_or_create(code="?", name=profile.organisation)
        institute.save()
        profile.institute = institute
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0003_auto_20200318_1058'),
    ]

    operations = [
        migrations.RunPython(make_institute),
    ]
