# Generated by Django 2.1.4 on 2019-08-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0003_digitalresourcegroup_current_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiosampleArtifact',
            fields=[
                ('majoraartifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifact')),
                ('sample_orig_id', models.CharField(max_length=24)),
                ('sample_type', models.CharField(max_length=24)),
                ('specimen_type', models.CharField(max_length=24)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('sample_longitude', models.PositiveSmallIntegerField(default=0)),
                ('sample_batch', models.PositiveSmallIntegerField(default=0)),
                ('sample_batch_longitude', models.PositiveSmallIntegerField(default=0)),
                ('registered_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifact',),
        ),
        migrations.CreateModel(
            name='BiosampleSource',
            fields=[
                ('majoraartifactgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactGroup')),
                ('source_type', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactgroup',),
        ),
    ]
