# Generated by Django 2.1.4 on 2019-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0005_labcheckinprocess_labcheckinprocessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubeartifact',
            name='sample_form',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='tubeartifact',
            name='tube_form',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
