# Generated by Django 2.2.10 on 2020-03-18 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0007_auto_20200318_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.TextField(default=uuid.UUID('9bf9bf38-820d-40ef-bf2c-519fb1bbeba9')),
        ),
    ]
