# Generated by Django 2.1.4 on 2019-08-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0007_auto_20190819_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResourceNode',
            fields=[
                ('majoraartifactgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactGroup')),
                ('node_name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactgroup',),
        ),
    ]
