# Generated by Django 2.1.4 on 2019-08-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0008_digitalresourcenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalresourceartifact',
            name='current_extension',
            field=models.CharField(default='', max_length=48),
        ),
        migrations.AddField(
            model_name='digitalresourceartifact',
            name='current_kind',
            field=models.CharField(default='File', max_length=48),
        ),
    ]
