# Generated by Django 2.1.4 on 2019-08-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0009_auto_20190819_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResourceCommand',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
                ('cmd_str', models.CharField(max_length=512)),
                ('return_code', models.SmallIntegerField(blank=True, null=True)),
                ('group_order', models.PositiveSmallIntegerField(default=0)),
                ('queued_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.CreateModel(
            name='DigitalResourceCommandGroup',
            fields=[
                ('majoraartifactprocessgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessGroup')),
                ('group_name', models.CharField(max_length=48)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessgroup',),
        ),
        migrations.CreateModel(
            name='DigitalResourceCommandPipelineGroup',
            fields=[
                ('majoraartifactprocessgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessGroup')),
                ('pipe_name', models.CharField(max_length=48)),
                ('orchestrator', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessgroup',),
        ),
        migrations.CreateModel(
            name='DigitalResourceCommandRecord',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
                ('resource_hash', models.CharField(max_length=64)),
                ('resource_size', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
    ]
