# Generated by Django 2.2.10 on 2020-03-18 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0009_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
