# Generated by Django 2.1.4 on 2019-08-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0010_digitalresourcecommand_digitalresourcecommandgroup_digitalresourcecommandpipelinegroup_digitalresour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactprocess',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='majora2.MajoraArtifactProcessGroup'),
        ),
    ]
