# Generated by Django 2.1.4 on 2019-08-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0011_auto_20190819_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactprocessgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_groups', to='majora2.MajoraArtifactProcessGroup'),
        ),
    ]
