# Generated by Django 2.1.4 on 2019-08-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0012_auto_20190819_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactprocessgroup',
            name='root_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_leaves', to='majora2.MajoraArtifactProcessGroup'),
        ),
    ]
