# Generated by Django 2.2.10 on 2020-03-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majora2', '0013_biosampleartifact_sample_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='submission_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_sample_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
