# Generated by Django 2.1.4 on 2019-08-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0013_majoraartifactprocessgroup_root_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifact',
            name='primary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_artifacts', to='majora2.MajoraArtifactGroup'),
        ),
    ]
