# Generated by Django 2.1.4 on 2019-08-20 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('majora2', '0014_auto_20190820_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajoraMetaRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta_tag', models.CharField(max_length=64)),
                ('meta_name', models.CharField(max_length=64)),
                ('value_type', models.CharField(max_length=48)),
                ('value', models.CharField(max_length=128)),
                ('link', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='majora2.MajoraArtifact')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='majora2.MajoraArtifactGroup')),
                ('pgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='majora2.MajoraArtifactProcessGroup')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majorametarecord_set+', to='contenttypes.ContentType')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='majora2.MajoraArtifactProcess')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
