# Generated by Django 2.2.10 on 2020-03-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0014_biosourcesamplingprocess_submission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosampleartifact',
            name='collection',
        ),
    ]
