# Generated by Django 2.1.4 on 2019-08-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majora2', '0016_majorametarecord_inheritable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favourited', to='majora2.MajoraArtifactGroup')),
                ('pgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favourited', to='majora2.MajoraArtifactProcessGroup')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
