# Generated by Django 2.1.4 on 2019-08-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0017_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='who',
            new_name='user',
        ),
    ]
