# Generated by Django 2.2.10 on 2020-03-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0018_auto_20200319_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasecallingProcess',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
                ('basecaller', models.CharField(max_length=48)),
                ('basecaller_version', models.CharField(blank=True, max_length=48, null=True)),
                ('basecaller_model', models.CharField(blank=True, max_length=48, null=True)),
                ('read_count', models.BigIntegerField(blank=True, null=True)),
                ('base_count', models.BigIntegerField(blank=True, null=True)),
                ('median_quality', models.FloatField(blank=True, null=True)),
                ('n50', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.CreateModel(
            name='BasecallingProcessRecord',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
        migrations.CreateModel(
            name='DNASequencingProcess',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
                ('instrument_make', models.CharField(max_length=64)),
                ('instrument_model', models.CharField(max_length=24)),
                ('flowcell_type', models.CharField(blank=True, max_length=48, null=True)),
                ('flowcell_id', models.CharField(blank=True, max_length=48, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.CreateModel(
            name='DNASequencingProcessGroup',
            fields=[
                ('majoraartifactprocessgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessGroup')),
                ('experiment_name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessgroup',),
        ),
        migrations.CreateModel(
            name='DNASequencingProcessRecord',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
        migrations.CreateModel(
            name='LibraryArtifact',
            fields=[
                ('majoraartifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifact')),
                ('library_strategy', models.CharField(blank=True, max_length=24, null=True)),
                ('library_source', models.CharField(blank=True, max_length=24, null=True)),
                ('library_selection', models.CharField(blank=True, max_length=24, null=True)),
                ('library_layout_config', models.CharField(blank=True, max_length=24, null=True)),
                ('library_layout_length', models.PositiveIntegerField(blank=True, null=True)),
                ('design_description', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifact',),
        ),
        migrations.CreateModel(
            name='LibraryPoolingProcess',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.CreateModel(
            name='LibraryPoolingProcessRecord',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
                ('barcode', models.CharField(blank=True, max_length=24, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
        migrations.AddField(
            model_name='biosampleartifact',
            name='taxonomy_identifier',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
