# Generated by Django 2.1.4 on 2019-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0018_auto_20190821_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifact',
            name='dice_name',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='majoraartifactgroup',
            name='dice_name',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='majoraartifactgroup',
            name='physical',
            field=models.BooleanField(default=False),
        ),
    ]
