# Generated by Django 2.1.4 on 2019-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0019_auto_20190823_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='processes',
            field=models.ManyToManyField(blank=True, related_name='tagged_processes', to='majora2.MajoraArtifactProcessGroup'),
        ),
    ]
