# Generated by Django 2.2.10 on 2020-03-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0019_auto_20200319_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biosampleartifact',
            old_name='sample_site',
            new_name='swab_site',
        ),
        migrations.RemoveField(
            model_name='majoraartifact',
            name='unique_name',
        ),
        migrations.AddField(
            model_name='biosampleartifact',
            name='central_sample_id',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='biosampleartifact',
            name='root_sample_id',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='biosampleartifact',
            name='sender_sample_id',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
    ]
