# Generated by Django 2.2.10 on 2020-03-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0020_auto_20200322_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biosampleartifact',
            old_name='swab_site',
            new_name='sample_site',
        ),
    ]
