# Generated by Django 2.1.4 on 2019-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0020_majoraartifactgroup_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactprocessgroup',
            name='dice_name',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='majoraartifactprocessgroup',
            name='meta_name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
