# Generated by Django 2.1.4 on 2019-10-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0021_auto_20190908_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcheckinprocessrecord',
            name='confusing',
            field=models.BooleanField(default=False),
        ),
    ]
