# Generated by Django 2.1.4 on 2019-10-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0022_labcheckinprocessrecord_confusing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiosourceSamplingProcess',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.CreateModel(
            name='BiosourceSamplingProcessRecord',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
        migrations.RemoveField(
            model_name='biosampleartifact',
            name='registered_date',
        ),
    ]
