# Generated by Django 2.2.10 on 2020-03-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0022_auto_20200322_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosampleartifact',
            name='secondary_accession',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
