# Generated by Django 2.2.10 on 2020-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0023_biosampleartifact_secondary_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosamplesource',
            name='secondary_id',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
