# Generated by Django 2.1.4 on 2019-10-08 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0023_auto_20191008_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactprocess',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majoraartifactprocess',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
