# Generated by Django 2.1.4 on 2019-10-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0024_auto_20191008_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifact',
            name='root_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descendants', to='majora2.MajoraArtifact'),
        ),
    ]
