# Generated by Django 2.2.10 on 2020-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0025_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='country_code',
            field=models.CharField(default='?', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
