# Generated by Django 2.1.4 on 2019-10-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0025_majoraartifact_root_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactprocessrecord',
            name='in_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='before_process', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AddField(
            model_name='majoraartifactprocessrecord',
            name='out_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_process', to='majora2.MajoraArtifactGroup'),
        ),
    ]
