# Generated by Django 2.1.4 on 2019-10-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0026_auto_20191008_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiosampleExtractionProcess',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
                ('extraction_method', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.CreateModel(
            name='BiosampleExtractionRecordProcess',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
    ]
