# Generated by Django 2.2.10 on 2020-03-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0027_auto_20200323_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryartifact',
            name='design_description',
        ),
        migrations.RemoveField(
            model_name='libraryartifact',
            name='library_selection',
        ),
        migrations.RemoveField(
            model_name='libraryartifact',
            name='library_source',
        ),
        migrations.RemoveField(
            model_name='libraryartifact',
            name='library_strategy',
        ),
        migrations.AddField(
            model_name='libraryartifact',
            name='pooling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library', to='majora2.LibraryPoolingProcess'),
        ),
        migrations.AddField(
            model_name='librarypoolingprocessrecord',
            name='library_selection',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='librarypoolingprocessrecord',
            name='library_source',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='librarypoolingprocessrecord',
            name='library_strategy',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
