# Generated by Django 2.1.4 on 2019-10-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('majora2', '0027_biosampleextractionprocess_biosampleextractionrecordprocess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiosampleExtractionRecordProcess',
            new_name='BiosampleExtractionProcessRecord',
        ),
    ]
