# Generated by Django 2.2.10 on 2020-03-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0028_auto_20200324_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryartifact',
            old_name='library_layout_config',
            new_name='layout_config',
        ),
        migrations.RenameField(
            model_name='libraryartifact',
            old_name='library_layout_length',
            new_name='layout_read_length',
        ),
        migrations.AddField(
            model_name='libraryartifact',
            name='layout_insert_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryartifact',
            name='seq_kit',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='libraryartifact',
            name='seq_protocol',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
