# Generated by Django 2.1.4 on 2019-11-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0028_auto_20191009_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majoraartifactprocess',
            options={'ordering': ['-when']},
        ),
        migrations.RenameField(
            model_name='digitalresourcecommandrecord',
            old_name='resource_hash',
            new_name='before_hash',
        ),
        migrations.RenameField(
            model_name='digitalresourcecommandrecord',
            old_name='resource_size',
            new_name='before_size',
        ),
    ]
