# Generated by Django 2.1.4 on 2019-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0029_auto_20191119_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalresourcecommandrecord',
            name='after_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalresourcecommandrecord',
            name='after_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
