# Generated by Django 2.2.10 on 2020-03-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0029_auto_20200324_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnasequencingprocess',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dnasequencingprocess',
            name='instrument_model',
            field=models.CharField(max_length=48),
        ),
    ]
