# Generated by Django 2.1.4 on 2019-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0030_auto_20191119_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalresourcecommandrecord',
            name='effect_status',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
    ]
