# Generated by Django 2.2.10 on 2020-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0030_auto_20200324_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biosampleartifact',
            old_name='sample_type',
            new_name='sample_type_collected',
        ),
        migrations.AlterField(
            model_name='majoraartifactgroup',
            name='unique_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
