# Generated by Django 2.1.4 on 2020-01-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0031_digitalresourcecommandrecord_effect_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majoraartifactprocess',
            name='group',
        ),
        migrations.AddField(
            model_name='tubeartifact',
            name='lid_label',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
