# Generated by Django 2.1.4 on 2020-01-25 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majora2', '0032_auto_20200110_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajoraArtifactQuarantinedProcess',
            fields=[
                ('majoraartifactprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcess')),
                ('note', models.CharField(max_length=255)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocess',),
        ),
        migrations.CreateModel(
            name='MajoraArtifactQuarantinedProcessRecord',
            fields=[
                ('majoraartifactprocessrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.MajoraArtifactProcessRecord')),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.majoraartifactprocessrecord',),
        ),
        migrations.CreateModel(
            name='MajoraArtifiactProcessComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifiactprocesscomment_set+', to='contenttypes.ContentType')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='majora2.MajoraArtifactProcess')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MajoraArtifiactProcessRecordComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifiactprocessrecordcomment_set+', to='contenttypes.ContentType')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='majora2.MajoraArtifactProcessRecord')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='majoraartifact',
            name='quarantined',
            field=models.BooleanField(default=False),
        ),
    ]
