# Generated by Django 2.1.4 on 2020-01-25 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majora2', '0033_auto_20200125_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajoraArtifactProcessComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifactprocesscomment_set+', to='contenttypes.ContentType')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='majora2.MajoraArtifactProcess')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='MajoraArtifactProcessRecordComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.majoraartifactprocessrecordcomment_set+', to='contenttypes.ContentType')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='majora2.MajoraArtifactProcessRecord')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.RemoveField(
            model_name='majoraartifiactprocesscomment',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='majoraartifiactprocesscomment',
            name='process',
        ),
        migrations.RemoveField(
            model_name='majoraartifiactprocesscomment',
            name='who',
        ),
        migrations.RemoveField(
            model_name='majoraartifiactprocessrecordcomment',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='majoraartifiactprocessrecordcomment',
            name='record',
        ),
        migrations.RemoveField(
            model_name='majoraartifiactprocessrecordcomment',
            name='who',
        ),
        migrations.DeleteModel(
            name='MajoraArtifiactProcessComment',
        ),
        migrations.DeleteModel(
            name='MajoraArtifiactProcessRecordComment',
        ),
    ]
