# Generated by Django 2.2.10 on 2020-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0034_abstractbioinformaticsprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnasequencingprocess',
            name='run_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
