# Generated by Django 2.1.4 on 2020-03-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0036_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosampleartifact',
            name='collection_date',
        ),
        migrations.AddField(
            model_name='biosampleartifact',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biosamples', to='majora2.BiosourceSamplingProcess'),
        ),
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='collection_location_adm0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='collection_location_adm1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
