# Generated by Django 2.2.10 on 2020-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0036_auto_20200327_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequencingprocess',
            name='run_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
