# Generated by Django 2.1.4 on 2020-03-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0037_auto_20200317_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='collection_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biosampleartifact',
            name='sample_orig_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
