# Generated by Django 2.2.10 on 2020-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0037_auto_20200327_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractbioinformaticsprocess',
            name='pipe_kind',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='abstractbioinformaticsprocess',
            name='pipe_name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='abstractbioinformaticsprocess',
            name='pipe_version',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.DeleteModel(
            name='BasecallingProcess',
        ),
        migrations.DeleteModel(
            name='BasecallingProcessRecord',
        ),
    ]
