# Generated by Django 2.1.4 on 2020-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0038_auto_20200317_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='unique_name',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
    ]
