# Generated by Django 2.1.4 on 2020-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0039_majoraartifactgroup_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifact',
            name='unique_name',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='biosampleartifact',
            name='sample_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='biosampleartifact',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
