# Generated by Django 2.1.4 on 2020-03-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0040_auto_20200317_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactprocess',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='majora2.MajoraArtifactProcessGroup'),
        ),
    ]
