# Generated by Django 2.2.10 on 2020-03-31 17:27

from django.db import migrations

def copy_pool(apps, schema_editor):
    LibraryArtifact = apps.get_model("majora2", "LibraryArtifact")
    for l in LibraryArtifact.objects.all():
        if l.pooling:
            l.created = l.pooling
            l.save()

class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0041_majoraartifact_created'),
    ]

    operations = [
        migrations.RunPython(copy_pool),
    ]
