# Generated by Django 2.1.4 on 2020-03-17 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0041_majoraartifactprocess_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactprocessrecord',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='majora2.MajoraArtifactProcess'),
        ),
    ]
