# Generated by Django 2.1.4 on 2020-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0042_auto_20200317_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='collection_location_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
