# Generated by Django 2.2.10 on 2020-03-31 17:35

from django.db import migrations

def copy_collection(apps, schema_editor):
    BiosampleArtifact = apps.get_model("majora2", "BiosampleArtifact")
    for b in BiosampleArtifact.objects.all():
        if b.collection:
            b.created = b.collection.process
            b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0043_remove_libraryartifact_pooling'),
    ]

    operations = [
        migrations.RunPython(copy_collection),
    ]
