# Generated by Django 2.2.10 on 2020-03-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0044_auto_20200331_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosampleartifact',
            name='collection',
        ),
    ]
