# Generated by Django 2.2.10 on 2020-04-05 12:32

from django.db import migrations

def copy_run_name(apps, schema_editor):
    DNASequencingProcess = apps.get_model("majora2", "DNASequencingProcess")
    for p in DNASequencingProcess.objects.all():
        if not p.run_group:
            p.run_group = p.run_name
            p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0046_auto_20200405_1232'),
    ]

    operations = [
        migrations.RunPython(copy_run_name),
    ]
