# Generated by Django 2.2.10 on 2020-04-05 16:24

from django.db import migrations

def copy_dar_dicename(apps, schema_editor):
    DigitalResourceGroup = apps.get_model("majora2", "DigitalResourceGroup")
    for g in DigitalResourceGroup.objects.all():
        if g.unique_name and g.unique_name.startswith("sequencing-dummy-tree") and not g.dice_name:
            g.dice_name = g.unique_name
            g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0047_auto_20200405_1232'),
    ]

    operations = [
        migrations.RunPython(copy_dar_dicename),
    ]
