# Generated by Django 2.2.10 on 2020-04-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0048_auto_20200405_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifact',
            name='dice_name',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='majoraartifact',
            name='meta_name',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
