# Generated by Django 2.2.10 on 2020-04-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0053_auto_20200411_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactprocessrecord',
            name='bridge_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_process', to='majora2.MajoraArtifact'),
        ),
        migrations.AlterField(
            model_name='majoraartifactprocessrecord',
            name='bridge_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_process', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AlterField(
            model_name='majoraartifactprocessrecord',
            name='in_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before_process', to='majora2.MajoraArtifact'),
        ),
        migrations.AlterField(
            model_name='majoraartifactprocessrecord',
            name='in_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before_process', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AlterField(
            model_name='majoraartifactprocessrecord',
            name='out_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_process', to='majora2.MajoraArtifact'),
        ),
        migrations.AlterField(
            model_name='majoraartifactprocessrecord',
            name='out_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_process', to='majora2.MajoraArtifactGroup'),
        ),
    ]
