# Generated by Django 2.2.10 on 2020-04-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0055_auto_20200419_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccessionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64)),
                ('primary_accession', models.CharField(max_length=64)),
                ('secondary_accesison', models.CharField(blank=True, max_length=64, null=True)),
                ('tertiary_accession', models.CharField(blank=True, max_length=64, null=True)),
                ('pag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessions', to='majora2.PublishedArtifactGroup')),
            ],
        ),
    ]
