# Generated by Django 2.2.10 on 2020-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0056_temporaryaccessionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedartifactgroup',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
