# Generated by Django 2.2.10 on 2020-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0058_auto_20200425_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalresourceartifact',
            name='current_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
