# Generated by Django 2.2.10 on 2020-04-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0060_dar_current_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarymajoraartifactmetric_mapping_tiles',
            old_name='pc_tiles_meancov_gte1',
            new_name='pc_tiles_medcov_gte1',
        ),
        migrations.RenameField(
            model_name='temporarymajoraartifactmetric_mapping_tiles',
            old_name='pc_tiles_meancov_gte10',
            new_name='pc_tiles_medcov_gte10',
        ),
        migrations.RenameField(
            model_name='temporarymajoraartifactmetric_mapping_tiles',
            old_name='pc_tiles_meancov_gte100',
            new_name='pc_tiles_medcov_gte100',
        ),
        migrations.RenameField(
            model_name='temporarymajoraartifactmetric_mapping_tiles',
            old_name='pc_tiles_meancov_gte20',
            new_name='pc_tiles_medcov_gte20',
        ),
        migrations.RenameField(
            model_name='temporarymajoraartifactmetric_mapping_tiles',
            old_name='pc_tiles_meancov_gte200',
            new_name='pc_tiles_medcov_gte200',
        ),
        migrations.RenameField(
            model_name='temporarymajoraartifactmetric_mapping_tiles',
            old_name='pc_tiles_meancov_gte5',
            new_name='pc_tiles_medcov_gte5',
        ),
        migrations.RenameField(
            model_name='temporarymajoraartifactmetric_mapping_tiles',
            old_name='pc_tiles_meancov_gte50',
            new_name='pc_tiles_medcov_gte50',
        ),
    ]
