# Generated by Django 2.2.10 on 2020-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0062_auto_20200425_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagqualitybasictestdecision',
            name='op',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pagqualitytest',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
