# Generated by Django 2.2.10 on 2020-04-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0063_auto_20200425_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagqualityreportdecisionrecord',
            name='is_fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagqualityreportrulerecord',
            name='is_fail',
            field=models.BooleanField(default=False),
        ),
    ]
