# Generated by Django 2.2.10 on 2020-04-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0064_auto_20200426_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagqualityreport',
            name='report_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='majora2.PAGQualityReportGroup'),
        ),
        migrations.AlterField(
            model_name='pagqualityreport',
            name='test_set_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='majora2.PAGQualityTestVersion'),
        ),
        migrations.AlterField(
            model_name='pagqualityreportdecisionrecord',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_as_a', to='majora2.PAGQualityReportRuleRecord'),
        ),
        migrations.AlterField(
            model_name='pagqualityreportdecisionrecord',
            name='b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions_as_b', to='majora2.PAGQualityReportRuleRecord'),
        ),
        migrations.AlterField(
            model_name='pagqualityreportdecisionrecord',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='majora2.PAGQualityReport'),
        ),
        migrations.AlterField(
            model_name='pagqualityreportrulerecord',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='majora2.PAGQualityReport'),
        ),
    ]
