# Generated by Django 2.2.10 on 2020-04-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0066_auto_20200427_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymajoraartifactmetric_sequence',
            name='pc_acgt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temporarymajoraartifactmetric_sequence',
            name='pc_invalid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temporarymajoraartifactmetric_sequence',
            name='pc_masked',
            field=models.FloatField(),
        ),
    ]
