# Generated by Django 2.2.10 on 2020-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0067_auto_20200428_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='sampling_strategy',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='source_category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='biosourcesamplingprocess',
            name='source_setting',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
