# Generated by Django 2.2.10 on 2020-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0068_auto_20200503_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagqualityreportequivalencegroup',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
