# Generated by Django 2.2.10 on 2020-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0072_auto_20200504_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='gisaid_opted',
            field=models.BooleanField(default=False),
        ),
    ]
