# Generated by Django 2.2.10 on 2020-05-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('majora2', '0073_institute_gisaid_opted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMajoraArtifactMetric_ThresholdCycle',
            fields=[
                ('temporarymajoraartifactmetric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.TemporaryMajoraArtifactMetric')),
                ('num_tests', models.PositiveIntegerField()),
                ('min_ct', models.FloatField()),
                ('max_ct', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.temporarymajoraartifactmetric',),
        ),
        migrations.CreateModel(
            name='TemporaryMajoraArtifactMetricRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to='majora2.TemporaryMajoraArtifactMetric')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_majora2.temporarymajoraartifactmetricrecord_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TemporaryMajoraArtifactMetricRecord_ThresholdCycle',
            fields=[
                ('temporarymajoraartifactmetricrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majora2.TemporaryMajoraArtifactMetricRecord')),
                ('ct_value', models.FloatField()),
                ('test_platform', models.CharField(blank=True, max_length=48, null=True)),
                ('test_target', models.CharField(blank=True, max_length=48, null=True)),
                ('test_kit', models.CharField(blank=True, max_length=48, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('majora2.temporarymajoraartifactmetricrecord',),
        ),
    ]
