# Generated by Django 2.2.10 on 2020-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0074_temporarymajoraartifactmetric_thresholdcycle_temporarymajoraartifactmetricrecord_temporarymajoraarti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymajoraartifactmetricrecord_thresholdcycle',
            name='ct_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
