# Generated by Django 2.2.10 on 2020-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0075_auto_20200505_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarypoolingprocessrecord',
            name='library_primers',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='librarypoolingprocessrecord',
            name='library_protocol',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
