# Generated by Django 2.2.10 on 2020-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0076_auto_20200507_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedartifactgroup',
            name='is_suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishedartifactgroup',
            name='suppressed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedartifactgroup',
            name='suppressed_reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
