# Generated by Django 2.2.10 on 2020-05-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0077_auto_20200506_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileapikey',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='profileapikey',
            name='was_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
