# Generated by Django 2.2.10 on 2020-05-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0077_auto_20200508_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryaccessionrecord',
            old_name='secondary_accesison',
            new_name='secondary_accession',
        ),
        migrations.AlterField(
            model_name='pagqualityreportequivalencegroup',
            name='pag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_groups', to='majora2.PublishedArtifactGroup'),
        ),
        migrations.AlterField(
            model_name='pagqualityreportgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='majora2.PAGQualityReportEquivalenceGroup'),
        ),
    ]
