# Generated by Django 2.2.10 on 2020-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0079_auto_20200515_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='ena_opted',
            field=models.BooleanField(default=True),
        ),
    ]
