# Generated by Django 2.2.10 on 2020-05-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0080_institute_ena_opted'),
        ('majora2', '0078_auto_20200506_1817'),
    ]

    operations = [
    ]
