# Generated by Django 2.2.10 on 2020-05-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0081_merge_20200520_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGUK_BiosourceSamplingProcessSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_surveillance', models.BooleanField()),
                ('is_hcw', models.BooleanField(null=True)),
                ('employing_hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employing_hospital_trust_or_board', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hospital_patient', models.BooleanField(null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admitted_hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admitted_hospital_trust_or_board', models.CharField(blank=True, max_length=100, null=True)),
                ('is_care_home_worker', models.BooleanField(null=True)),
                ('is_care_home_resident', models.BooleanField(null=True)),
                ('anonymised_care_home_code', models.CharField(blank=True, max_length=3, null=True)),
                ('admitted_with_covid_diagnosis', models.BooleanField(null=True)),
                ('sampling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coguk_supp', to='majora2.BiosourceSamplingProcess')),
            ],
        ),
    ]
