# Generated by Django 2.2.10 on 2020-05-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0082_coguk_biosourcesamplingprocesssupplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coguk_biosourcesamplingprocesssupplement',
            name='sampling',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coguk_supp', to='majora2.BiosourceSamplingProcess'),
        ),
    ]
