# Generated by Django 2.2.10 on 2020-05-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0083_auto_20200520_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coguk_biosourcesamplingprocesssupplement',
            name='is_surveillance',
            field=models.BooleanField(null=True),
        ),
    ]
