# Generated by Django 2.2.10 on 2020-05-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0086_migrate_s_strategy_to_supp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosourcesamplingprocess',
            name='sampling_strategy',
        ),
        migrations.RemoveField(
            model_name='biosourcesamplingprocess',
            name='source_category',
        ),
        migrations.RemoveField(
            model_name='biosourcesamplingprocess',
            name='source_setting',
        ),
    ]
