# Generated by Django 2.2.10 on 2020-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0087_auto_20200520_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactprocess',
            name='majora_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
