# Generated by Django 2.2.10 on 2020-05-21 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0088_majoraartifactprocess_majora_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactprocess',
            name='majora_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
