# Generated by Django 2.2.10 on 2020-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0089_auto_20200521_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coguk_biosourcesamplingprocesssupplement',
            name='anonymised_care_home_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
