# Generated by Django 2.2.10 on 2020-05-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0091_auto_20200527_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_approve_profiles', 'Can approve new user profiles for their organisation'), ('can_grant_profile_permissions', 'Can grant other users permissions that change the Profile system')]},
        ),
    ]
