# Generated by Django 2.2.10 on 2020-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0092_auto_20200527_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_site_approved',
            field=models.BooleanField(default=False),
        ),
    ]
