# Generated by Django 2.2.10 on 2020-05-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0094_approve_already_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'permissions': [('can_register_institute', 'Can register a new institute in Majora')]},
        ),
    ]
