# Generated by Django 2.2.10 on 2020-05-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0095_auto_20200527_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_approve_profiles', 'Can approve new user profiles for their organisation'), ('can_approve_profiles_via_bot', 'Can approve new user profiles for any organisation via the bot system'), ('can_grant_profile_permissions', 'Can grant other users permissions that change the Profile system')]},
        ),
        migrations.AddField(
            model_name='profile',
            name='slack_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slack_verified',
            field=models.BooleanField(default=False),
        ),
    ]
