# Generated by Django 2.2.10 on 2020-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0096_auto_20200527_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='coguk_biosourcesamplingprocesssupplement',
            name='is_icu_patient',
            field=models.BooleanField(null=True),
        ),
    ]
