# Generated by Django 2.2.10 on 2020-06-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0097_coguk_biosourcesamplingprocesssupplement_is_icu_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedartifactgroup',
            options={'permissions': [('temp_can_read_pags_via_api', 'Can read published artifact groups via the API')]},
        ),
    ]
