# Generated by Django 2.2.10 on 2020-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0098_auto_20200606_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileapikeydefinition',
            name='permission',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
