# Generated by Django 2.2.10 on 2020-06-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0099_profileapikeydefinition_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileapikeydefinition',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Permission'),
        ),
    ]
