# Generated by Django 2.2.10 on 2020-07-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0100_auto_20200606_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAgreementDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=96, unique=True)),
                ('description', models.CharField(max_length=256, unique=True)),
                ('content', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('proposal_timestamp', models.DateTimeField()),
                ('effective_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_timestamp', models.DateTimeField()),
                ('is_terminated', models.BooleanField(default=False)),
                ('terminated_reason', models.CharField(blank=True, max_length=24, null=True)),
                ('terminated_timestamp', models.DateTimeField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majora2.ProfileAgreementDefinition')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majora2.Profile')),
            ],
        ),
    ]
