# Generated by Django 2.2.10 on 2020-07-13 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0101_profileagreement_profileagreementdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileagreement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profileagreementdefinition',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='profileagreementdefinition',
            name='name',
            field=models.CharField(max_length=96),
        ),
    ]
