# Generated by Django 2.2.10 on 2020-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0102_auto_20200713_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileagreement',
            name='terminated_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
