# Generated by Django 2.2.10 on 2020-07-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0103_auto_20200713_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_code', models.CharField(max_length=10, unique=True)),
                ('lab_name', models.CharField(blank=True, max_length=512, null=True)),
                ('lab_addr', models.CharField(blank=True, max_length=512, null=True)),
                ('lab_list', models.CharField(blank=True, max_length=2048, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='majora2.Institute')),
            ],
        ),
    ]
