# Generated by Django 2.2.13 on 2020-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0104_institutecredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutecredit',
            name='credit_code',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
