# Generated by Django 2.2.10 on 2020-07-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0105_auto_20200715_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileagreementdefinition',
            name='is_terminable',
            field=models.BooleanField(default=True),
        ),
    ]
