# Generated by Django 2.2.10 on 2020-07-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0107_majoradataview_majoradataviewserializerfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoradataviewserializerfield',
            name='dataview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='majora2.MajoraDataview'),
        ),
    ]
