# Generated by Django 2.2.13 on 2020-07-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0108_auto_20200716_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajoraDataviewUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_start', models.DateTimeField(blank=True, null=True)),
                ('validity_end', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.CharField(blank=True, max_length=24, null=True)),
                ('revoked_timestamp', models.DateTimeField(blank=True, null=True)),
                ('dataview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='majora2.MajoraDataview')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='majora2.Profile')),
            ],
        ),
    ]
