# Generated by Django 2.2.13 on 2020-07-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0109_majoradataviewuserpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majoradataview',
            options={'permissions': [('can_read_dataview', 'Can read the contents of data views via the API')]},
        ),
    ]
