# Generated by Django 2.2.13 on 2020-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0111_auto_20200717_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryaccessionrecord',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='temporaryaccessionrecord',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporaryaccessionrecord',
            name='public_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryaccessionrecord',
            name='rejected_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryaccessionrecord',
            name='requested_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryaccessionrecord',
            name='terminated_reason',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryaccessionrecord',
            name='primary_accession',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
