# Generated by Django 2.2.13 on 2020-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0112_auto_20200729_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryaccessionrecord',
            old_name='terminated_reason',
            new_name='rejected_reason',
        ),
        migrations.AlterField(
            model_name='temporaryaccessionrecord',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
