# Generated by Django 2.2.13 on 2020-07-29 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majora2', '0113_auto_20200729_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryaccessionrecord',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
