# Generated by Django 2.2.13 on 2020-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0114_temporaryaccessionrecord_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='group_path',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
