# Generated by Django 2.2.13 on 2020-08-08 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0115_majoraartifactgroup_group_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajoraArtifactGroupLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('from_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_glinks', to='majora2.MajoraArtifactGroup')),
                ('to_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_glinks', to='majora2.MajoraArtifact')),
                ('to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_glinks', to='majora2.MajoraArtifactGroup')),
            ],
        ),
    ]
