# Generated by Django 2.2.13 on 2020-08-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0116_majoraartifactgrouplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactgrouplink',
            name='from_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_glinks', to='majora2.MajoraArtifactGroup'),
        ),
        migrations.AlterField(
            model_name='majoraartifactgrouplink',
            name='link_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
