# Generated by Django 2.2.13 on 2020-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0117_auto_20200808_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoraartifactgroup',
            name='temp_kind',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
