# Generated by Django 2.2.13 on 2020-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0118_majoraartifactgroup_temp_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoradataview',
            name='entry_point',
            field=models.CharField(default='PublishedArtifactGroup', max_length=128),
            preserve_default=False,
        ),
    ]
