# Generated by Django 2.2.13 on 2020-08-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0119_majoradataview_entry_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majoradataview',
            options={'permissions': [('can_read_dataview_via_api', 'Can read the contents of CONSORTIUM data views via the API'), ('can_read_restricted_dataview_via_api', 'Can read the contents of RESTRICTED data views via the API')]},
        ),
    ]
