# Generated by Django 2.2.13 on 2020-08-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('majora2', '0120_auto_20200814_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoradataview',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Permission'),
        ),
    ]
