# Generated by Django 2.2.13 on 2020-08-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0121_majoradataview_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileapikey',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='majora2.Profile'),
        ),
    ]
