# Generated by Django 2.2.13 on 2020-08-27 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatl', '0024_oauth2codeonlyapplication'),
        ('majora2', '0122_auto_20200820_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAppPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=64)),
                ('validity_start', models.DateTimeField(blank=True, null=True)),
                ('validity_end', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_passwords', to='majora2.Profile')),
            ],
        ),
    ]
