# Generated by Django 2.2.13 on 2020-09-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0124_majoradataviewfilterfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileagreement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='majora2.Profile'),
        ),
    ]
