# Generated by Django 2.2.13 on 2020-10-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0126_auto_20200928_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalresourceartifact',
            name='current_name',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
