# Generated by Django 2.2.13 on 2020-10-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0127_auto_20201009_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoraartifactprocess',
            name='hook_name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
