# Generated by Django 2.2.13 on 2020-10-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0129_coguk_biosourcesamplingprocesssupplement_collection_pillar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedartifactgroup',
            options={'permissions': [('temp_can_read_pags_via_api', 'Can read published artifact groups via the API'), ('can_suppress_pags_via_api', 'Can suppress any published artifact group via the API')]},
        ),
    ]
