# Generated by Django 2.2.13 on 2020-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0130_auto_20201029_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosamplesource',
            name='root_biosample_source_id',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
