# Generated by Django 2.2.13 on 2020-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0131_biosamplesource_root_biosample_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosamplesource',
            name='root_biosample_source_id',
        ),
        migrations.AddField(
            model_name='biosampleartifact',
            name='root_biosample_source_id',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
