# Generated by Django 2.2.13 on 2020-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0133_auto_20201105_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
