# Generated by Django 2.2.13 on 2021-01-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0136_institute_ena_assembly_opted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymajoraartifactmetric',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='majora2.MajoraArtifact'),
        ),
    ]
