# Generated by Django 2.2.13 on 2021-04-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0139_auto_20210305_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majoraartifact',
            options={'permissions': [('view_majoraartifact_info', 'Can view basic information of any artifact')]},
        ),
    ]
