# Generated by Django 2.2.24 on 2021-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0141_auto_20210525_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryartifact',
            name='seq_kit',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='libraryartifact',
            name='seq_protocol',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
