# Generated by Django 2.2.24 on 2022-01-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0143_auto_20220105_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_revoke_profiles', 'Can revoke the access of any user'), ('can_approve_profiles', 'Can approve new user profiles for their organisation'), ('can_approve_profiles_via_bot', 'Can approve new user profiles for any organisation via the bot system'), ('can_grant_profile_permissions', 'Can grant other users permissions that change the Profile system'), ('can_wildcard_sequencing_runs', 'Can use the wildcard character to unroll all sequencing runs in Majora')]},
        ),
    ]
