# Generated by Django 2.2.26 on 2022-01-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0146_majora_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorafact',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='majorafact',
            constraint=models.UniqueConstraint(fields=('namespace', 'key'), name='is_only_key_in_namespace'),
        ),
    ]
