# Generated by Django 2.2.26 on 2022-01-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0147_majora_fact_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorafact',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
