# Generated by Django 2.2.26 on 2022-02-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0148_majora_fact_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='credit_code_only',
            field=models.BooleanField(default=False),
        ),
    ]
