# Generated by Django 2.2.26 on 2022-02-26 16:00

from django.db import migrations

def assign_uniquename(apps, schema_editor):
    DNASequencingProcessRecord = apps.get_model("majora2", "DNASequencingProcessRecord")
    DNASequencingProcess = apps.get_model("majora2", "DNASequencingProcess")
    for record in DNASequencingProcessRecord.objects.all():
        run = DNASequencingProcess.objects.get(id=record.process.id)
        run_name = run.run_name
        library_name = record.in_artifact.dice_name
        record.unique_name = "%s-%s" % (run_name, library_name)
        record.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('majora2', '0151_auto_20220226_1624'),
    ]

    operations = [
        migrations.RunPython(assign_uniquename)
    ]
